name: ci
on:
  workflow_dispatch: #github页面手动触发
  push:
    tags:
      - v*
env:
  IMAGE_NAME: gpt4free #这是您的镜像名
jobs:
  get-tags:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
      - name: Extract version number
        id: get-version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "${GITHUB_REF#refs/tags/v}" > version.txt
          else
            echo "edge" > version.txt
          fi
      - name: Set outputs
        run: |
          echo ::set-env name=TAGS::$(cat version.txt)
        shell: bash        
  push-ghcr:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.get-tags.outputs.TAGS }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest   
