name: Build and Push Docker Image to ghcr.io

on:
  push:
    branches:
      - xmp2008-patch-1

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v2

      -
        name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gpt4free:latest
