name: Publish Docker Image
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Set image timezone to Asia/Shanghai
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.ref }}
          dockerfile: ./Docker/Dockerfile
          build-args: |
            --build-arg TZ=Asia/Shanghai
